- name: Patching Debian
  include_tasks: debian.yml
  when: ansible_facts.os_family | lower == 'debian'

- name: Patching Windows
  include_tasks: windows.yml
  when: ansible_facts.os_family | lower == 'windows'
